### ISSUE TITLE
Support for types for CodeBlock and CopyBlock.

### ISSUE THREAD

**Issue by Andrew2432** [rajinwonderland/react-code-blocks#16]
I would like to have support for prop types for components such as `CodeBlock` and `CopyBlock` using TypeScript. Is there any way to provide types for these components?

I want to implement like this:

```jsx
type Props = CodeBlockProps;
const Example: React.FC<Props> = (props: Props) => {
 return (
  <CodeBlock {...props} language="jsx" />
  );
}
```

**Comment by rajinwonderland** [comment]
Hey @Andrew2432 

Good question, I haven't really had much of a chance to standardize the typing for the components yet, especially since they're borrowing a lot of their props from `react-syntax-highlighter`. 

I think adding support for a definitely typed package would be swell! If you'd like to help by submitting a PR I'd really appreciate your help!

Otherwise, I'll add this as an enhancement for a future release.

For now, you can try to adopt the types from the components themselves which are listed below:

- [`CopyBlock.tsx`](https://www.github.com/rajinwonderland/react-code-blocks/tree/master/packages%2Freact-code-blocks%2Fsrc%2Fcomponents%2FCopyBlock.tsx)

- [`CodeBlock.tsx`](https://www.github.com/rajinwonderland/react-code-blocks/tree/master/packages%2Freact-code-blocks%2Fsrc%2Fcomponents%2FCodeBlock.tsx)


Another reason I've been holding off on this is I would like to adopt a better theming convention (perhaps something similar to theme-ui) which may drastically alter the types in the future.

**Comment by Andrew2432** [comment]
Cool. I might try to develop the required DefinetlyTyped library for this project. If I do, I will make a PR. 

Thanks for providing the component types.

P.S. This project is lit. I'm using it on my Gatsby powered website.

**Comment by rajinwonderland** [comment]
@Andrew2432 that would be much appreciated!

Thanks, I'm glad to hear it! Yeah I really just wanted to have some cool code themes on a Gatsby site, which inspired me to build this! I'm glad it's coming handy!

**Comment by ChuckJonas** [comment]
The types for these components seem off (missing partial designation). When you try to use a component, it tells you all these optional props are required...
