### ISSUE TITLE
Styles are not working with Bootstrap Css

### ISSUE THREAD

**Issue by indranildeveloper** [rajinwonderland/react-code-blocks#66]
When we are using Bootstrap and react-code-blocks then the theme changes quite a bit
<img width="1423" alt="Screenshot 2022-08-01 at 8 32 40 PM" src="https://user-images.githubusercontent.com/73965619/182180396-c42d5379-1dbc-4a26-9392-8030ecbc2a5f.png">

The above image shows the dracula theme. Is there any way to fix that?

**Comment by bncbodrogi** [comment]
Hopefully, you solved this since but it might help someone else.

From Bootstrap 5.2.x there is a `--bs-code-color` css custom property set, as far as I can tell it is `#d63384` by default.
This will overwrite the colour of the majority of your text in the code block, but not everything.

You can correct this by adding the following block to your css file.
```css
:root {
    --bs-code-color: #bbbbbb;
}
```

Resources:
*  https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties
* https://getbootstrap.com/docs/5.2/customize/css-variables/

**Comment by indranildeveloper** [comment]
Ok, Thank you.
